=== M1INFOS2/projetxml/projet_dtd.dtd
<!-- 
	
	DTD liée à la représentation des unités d'enseignement du Master,
	les enseignants, les parcours et les semestres.

	Quentin CHEYNET
	Sébastien DELECRAZ
	
	Dernières modifications : 08/02/2014
	
 -->

<!ENTITY luminy  			"Luminy">
<!ENTITY stjerome			"Saint Jerome">
<!ENTITY amusciences		"UFR Sciences, Université d'Aix-Marseille">

<!ELEMENT master   			(personnes,matières,spécialités)>
<!ELEMENT personnes			(personne+)>
<!ELEMENT matières			(matière+)>
<!ELEMENT spécialités		(spécialité+)>

<!ELEMENT nom 				(#PCDATA)>

<!ELEMENT spécialité      	(nom,code,finalité?,lieu+,ref-responsable+,description,parcours+)>
<!ATTLIST spécialité        année  (M1|M2) #REQUIRED>
<!ELEMENT code      		(#PCDATA)>
<!ELEMENT finalité      	(#PCDATA)>
<!ELEMENT lieu      		(#PCDATA)>
<!ELEMENT description		(p)>

<!ELEMENT ref-responsable 	EMPTY>
<!ATTLIST ref-responsable  	ref  IDREF  #REQUIRED>

<!ELEMENT ref-intervenant 	EMPTY>
<!ATTLIST ref-intervenant  	ref  IDREF  #REQUIRED>

<!ELEMENT personne			(nom,établissement,email,site_web?)>
<!ATTLIST personne 			id ID #REQUIRED>
<!ELEMENT établissement		(#PCDATA)>
<!ELEMENT email				(#PCDATA)>
<!ELEMENT site_web			(#PCDATA)>

<!ELEMENT parcours      	(nom,code,ref-responsable,présentation,lieu+,programme,programme,info*)>
<!ELEMENT programme      	(ref-matière+)>
<!ATTLIST programme 		semestre (S1|S2|S3|S4) #REQUIRED>
<!ELEMENT présentation		     	(#PCDATA)>

<!ELEMENT matière			(nom,ref-intervenant*,résumé,crédits,horaire_c_td_tp?)>
<!ATTLIST matière			type (optionelle|obligatoire) #REQUIRED
							id ID #REQUIRED>
<!ELEMENT ref-matière		EMPTY>
<!ATTLIST ref-matière	  	ref  IDREF  #REQUIRED>
<!ELEMENT résumé			(p)>
<!ELEMENT crédits			(#PCDATA)>
<!ELEMENT horaire_c_td_tp	(#PCDATA)>

<!ELEMENT p					(#PCDATA|i|g|liste|tab)*>
<!ELEMENT i					(#PCDATA)>
<!ELEMENT g					(#PCDATA)>
<!ELEMENT liste				(p,p+)>

<!ELEMENT tab				(ligne+)>
<!ELEMENT ligne             (cell+)>
<!ATTLIST ligne				tete-col (oui|non) 'non'>
<!ELEMENT cell              (p)>
<!ATTLIST cell				tete-ligne (oui|non) 'non'>

<!ELEMENT info				(titre,p)>
<!ELEMENT titre				(#PCDATA)>

=== M1INFOS2/projetxml/projet.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE master SYSTEM "projet_dtd.dtd">

<master>
	<personnes>
		<personne id="lugiez">
			<nom>Denis LUGIEZ</nom>
			<établissement>&amusciences;</établissement>
			<email>denis.lugiez@univ-amu.fr</email>
		</personne>
		<personne id="massat">
			<nom>Jean-Luc MASSAT</nom>
			<établissement>&amusciences;</établissement>
			<email>jean-luc.massat@univ-amu.fr</email>
		</personne>
		<personne id="novelli">
			<nom>Noël Novelli</nom>
			<établissement>&amusciences;</établissement>
			<email>noel.novelli@univ-amu.fr</email>
		</personne>
		<personne id="tichit">
			<nom>Laurent Tichit</nom>
			<établissement>&amusciences;</établissement>
			<email>laurent.tichit@univ-amu.fr</email>
		</personne>
		<personne id="creignou">
			<nom>Nadia Creignou</nom>
			<établissement>&amusciences;</établissement>
			<email>nadia.creignou@univ-amu.fr</email>
		</personne>
		<personne id="frederic">
			<nom>Olive Frederic</nom>
			<établissement>&amusciences;</établissement>
			<email>olive.frederic@univ-amu.fr</email>
		</personne>
		<personne id="godard">
			<nom>Emanuel Godard</nom>
			<établissement>&amusciences;</établissement>
			<email>emanuel.godard@univ-amu.fr</email>
		</personne>
		<personne id="santocanale">
			<nom>Luigi Santocanale</nom>
			<établissement>&amusciences;</établissement>
			<email>luigi.santocanale@univ-amu.fr</email>
		</personne>
		<personne id="couetoux">
			<nom>Basil Couetoux</nom>
			<établissement>&amusciences;</établissement>
			<email>basil.couetoux@univ-amu.fr</email>
		</personne>
		<personne id="morin">
			<nom>Rémi Morin</nom>
			<établissement>&amusciences;</établissement>
			<email>remi.morin@univ-amu.fr</email>
		</personne>
	</personnes>

	<matières>
		<matière id="anglais2" type="obligatoire">
			<nom>Anglais 2</nom>
			<résumé>
				<p>
					Expression orale et écrite : exposés sur des sujets scientifiques
					et / ou professionnels, travaux écrits. Préparation et passage du
					TOEIC.
				</p>
			</résumé>
			<crédits>3</crédits>
		</matière>
		<matière id="communication2" type="obligatoire">
			<nom>Communication 2</nom>
			<résumé>
				<p>
					Connaître le monde de l'entreprise. Positionner son projet
					professionnel. Réussir un recrutement, un stage professionnel ou un
					emploi. Identifier et situer ses aptitudes et ses compétences.
					Clarifier ses motivations et leurs incidences sur un parcours ou
					des choix professionnels.
				</p>
			</résumé>
			<crédits>3</crédits>
		</matière>

		<matière id="GL" type="obligatoire">
			<nom>Géniel Logiciel</nom>
			<ref-intervenant ref="novelli" />
			<ref-intervenant ref="tichit" />
			<résumé>
				<p>
					Processus logiciel - Gestion de projet - Spécification et
					conception (artefact : notation UML) - Design patterns
				</p>
			</résumé>
			<crédits>6</crédits>
			<horaire_c_td_tp>20h/20h/20h</horaire_c_td_tp>
		</matière>
		<matière id="Complexité" type="obligatoire">
			<nom>Complexité</nom>
			<ref-intervenant ref="creignou" />
			<ref-intervenant ref="frederic" />
			<résumé>
				<p>
					Rappels sur les notions d'analyse de la complexité des
					algorithmes et des problèmes. - Notion de problèmes (décision,
					recherche, dénombrement, énumération, optimisation). Bornes
					inférieures de complexité. - Classes P et NP. Problèmes
					NP-complets. - Méthodes de résolution des problèmes NP-Complets.
				</p>
			</résumé>
			<crédits>6</crédits>
			<horaire_c_td_tp>20h/20h/20h</horaire_c_td_tp>
		</matière>
		<matière id="Réseaux" type="obligatoire">
			<nom>Réseaux</nom>
			<ref-intervenant ref="godard" />
			<résumé>
				<p>
					Architecture en couches, standard OSI - Couche physique - Couche
					liaison de Données - Réseau IP - Algorithmes de routage, routage IP
					- Protocole TCP/IP - Couche Application : HTTP, SMTP, FTP, ... -
					Bases des protocoles cryptographiques (terminologie, architecture à
					clef publique). - Introduction à la Sécurité des réseaux.
				</p>
			</résumé>
			<crédits>6</crédits>
			<horaire_c_td_tp>20h/20h/20h</horaire_c_td_tp>
		</matière>
		<matière id="progfonct" type="obligatoire">
			<nom>Programmation fonctionnelle</nom>
			<ref-intervenant ref="santocanale" />
			<ref-intervenant ref="couetoux" />
			<résumé>
				<p>
					Introduction à la programmation fonctionnelle, sur l'exemple du
					langage OCaml Expressions, évaluation, types de base.
					Polymorphisme, ordre supérieur. Fonctions récursives, filtrage. Les
					diverses stratégies d'évaluation, application à la programmation
					d'un opérateur de point fixe. 2- Les types Sommes, types récursifs,
					polymorphes. Arbres. Filtrage. 3- Sémantique opérationnelle
					Liaisons, environnements, clôtures. Évaluation des fonctions
					récursives . 4- Aspects impératifs Exceptions, entrées-sorties,
					séquencement, fichiers, références, tableaux, enregistrements. 5-
					Implantation du filtrage en OCaml Termes formels, substitutions,
					filtrage.
				</p>
			</résumé>
			<crédits>3</crédits>
			<horaire_c_td_tp>10h/10h/10h</horaire_c_td_tp>
		</matière>
		<matière id="progpara" type="obligatoire">
			<nom>Programmation fonctionnelle</nom>
			<ref-intervenant ref="morin" />
			<résumé>
				<p>
					Ma position est que dans programmation parallèle, on fait de la
					programmation multithread en JAVA, en tâchant d'être rigoureux :
					présentation des problèmes et des solutions algorithmiques ;
					classes utiles ; construction de classe threadsafe ; détail de
					modèle mémoire Java et garantie DRF. Cette année j'ai ajouté
					vérification formelle d'algorithmes parallèles (ou distribués).
				</p>
			</résumé>
			<crédits>3</crédits>
			<horaire_c_td_tp>10h/10h/10h</horaire_c_td_tp>
		</matière>
		<matière id="proglog" type="optionelle">
			<nom>Programmation logique</nom>
			<résumé>
				<p>
					Introduction. Forme générale des règles. Effacement, unification,
					backtracking. Contrôle de l'exécution. - Listes, arbres et
					n-uplets. Liste représentée par différence de listes. Ajout en tête
					et en queue, concaténation. - Analyseurs syntaxiques. Construction
					d'un arbre syntaxique. Liste des feuilles d'un arbre. Freeze et
					analyse par feuille. - Règles prédéfinies.
				</p>
			</résumé>
			<crédits>3</crédits>
			<horaire_c_td_tp>10h/10h/10h</horaire_c_td_tp>
		</matière>
		<matière id="outils_internet" type="optionelle">
			<nom>Outils de l'internet</nom>
			<résumé>
				<p>
					Présentation d'Internet. - Les langages et les normes sur
					Internet. - Les protocoles : HTTP, HTTP, SMTP, IMAP, POP3 - Les
					applications web. - Sécurité. - Les nouvelles et futures
					technologies.
				</p>
			</résumé>
			<crédits>3</crédits>
			<horaire_c_td_tp>10h/10h/10h</horaire_c_td_tp>
		</matière>

		<matière id="sys_embarque" type="optionelle">
			<nom>Système embarqué</nom>
			<résumé>
				<p>
					nous sommes désolé, mais nous n'avons pas encore de résumé.
				</p>
			</résumé>
			<crédits>3</crédits>
			<horaire_c_td_tp>10h/10h/10h</horaire_c_td_tp>
		</matière>
		<matière id="FIL" type="optionelle">
			<nom>Fondamentaux pour l'ingénierie des langues</nom>
			<résumé>
				<p>
					Rappel de théorie des langages - Algorithmes d'analyse syntaxique
					pour grammaires ambiguës - Transducteurs finis et leur application
					en TAL
				</p>
			</résumé>
			<crédits>3</crédits>
			<horaire_c_td_tp>10h/10h/10h</horaire_c_td_tp>
		</matière>
		<matière id="MED" type="optionelle">
			<nom>Modèles à évènements discrets</nom>
			<résumé>
				<p>
					Posséder les notions de base en modélisation et analyse de
					systèmes dynamiques à événements discrets et particulièrement
					appréhender le formalisme réseau de Pétri. Étudier la conception et
					la spécification des systèmes réactifs à travers l'analyse du
					modèle à évènements discrets (concurrence, parallélisme,
					synchronisation).
				</p>
			</résumé>
			<crédits>3</crédits>
			<horaire_c_td_tp>C/TD 20h/10h</horaire_c_td_tp>
		</matière>
		<matière id="IAA" type="optionelle">
			<nom>Introduction à l'apprentissage automatique</nom>
			<résumé>
				<p>
					Introduction aux concepts de bases : formalisme statistique,
					erreur de généralisation - Arbres de décision : algorithme ID3,
					élagage, programmation - Algorithme du perceptron : algorithme,
					temps de convergence, propriétés de généralisation, application à
					la classification de textes - Régression logistique : cadre
					probabiliste, maximisation de la vraisemblance, optimisation par
					gradient conjugué et méthode de Newton, application à la
					classification de textes - Quelques éléments théoriques : notion de
					capacité de classes de fonctions, complexité de Rademacher, borne
					dépendante des données.
				</p>
			</résumé>
			<crédits>3</crédits>
			<horaire_c_td_tp>10h/10h/10h</horaire_c_td_tp>
		</matière>

		<matière id="anglais1" type="obligatoire">
			<nom>Anglais</nom>
			<résumé>
				<p>
					Un enseignement destiné à confirmer l'utilisation de l'anglais
					dans le contexte de l'informatique ainsi que dans la pratique
					professionnelle.
				</p>
			</résumé>
			<crédits>3</crédits>
			<horaire_c_td_tp>10h/10h/10h</horaire_c_td_tp>
		</matière>
		<matière id="communication1" type="obligatoire">
			<nom>Communication</nom>
			<résumé>
				<p>
					chapitre 1 : Théories de la communication : 1.1 La théorie
					mathématique de l’information (Shannon, Weaver), la cybernétique
					(Wiener) 1.2 La théorie de Palo Alto ( Bateson, Watzlawick) et la
					théorie de la communication par les processus (Mucchielli) chapitre
					2 : Rôle de l’interculturalité dans le travail en équipe : 2.1
